---
title: "立法院質詢稿分析"
author: "李庭偉"
date: "1-11-2017"
output: html_document
---



## W7 Grouphomework/ Group8

#分析資料：


截取自立法院公報的質詢內容檔案(內容多是錄音轉譯稿)


##發想問題&問題意識：


1.立委的質詢風格跟備質詢的長官態度是否有可能從對談紀錄中觀察得知？

2.委員的發言的意識形態，跟該黨的意識型態的距離?是否委員都只遵循黨意而罔顧民意?可以試圖從各黨的黨綱資料或是歷次選舉政策白皮書建立一個政黨政策意識形態量表；在與黨籍委員的發言做對照。

3.內閣官員有無黨籍是否影響詢答的效果，官員會不會因為有黨籍而比較「不怕」委員的質詢，反而比較容易迴避問題或對立委態度強硬?

4.問答雙方的內容是否都有效率？包含提問是不是引用適切的論述？回答時會不會正面去回應問題，還是會使用像是「我們」、「未來」等較空泛詞彙，迴避訂立一個實際的時間目標或是界定當責單位，而造成質詢沒有效率？

5.了解立委關注的議題取向？


#分析方法：


1.可用語料庫分析常見的vocabulary practice理論，就是把文本裡每個詞彙的選用都視為「具動機的、有目的性的」，因此只要計算字詞頻、再觀察前後搭配詞彙，便可看字彙運用的文化意義和意識形態。

2.潛在語義分析Latent Semantic Analysis
將索引詞(關注主題)和質詢內容，透過LSA運算方法畫在二維圖上，可以大致看出立委關注的議題種類。
索引詞可透過每個委員提到的主題進行篩選，被兩位以上委員提到的詞可視為索引詞。
這也能用在分析立委的質詢風格上(把索引詞聚焦在一些態度用語，索引詞應該就能變成分類質詢態度或口氣的類別了)


#可能遇到的技術問題：


1.標題、副標題和內文間有重複，會影響到詞頻計算（比方說段落標題提起改革教育文化，下面內文裡也多次呼應）。

2.我們要怎麼確定哪句話是誰講的？例如我們在意黨籍立委的發言、官員的回答的內容，但是我們要怎麼把這些語料分類成是「誰說的話」，以及「是誰跟誰的對話」。



#理論問題：

1.遇到一詞多義難解，SVD跟中間的運算不好裡解。

2.個文本前半部內容是寫好的演講稿，是written-to-be-spoken，可以說是半書面。而後半部則是質詢的逐字稿，為spoken-to-be-written，是接近口語的。混在一起分析時，有些詞頻特別突出的情況就需要篩選掉。

3.代名詞使用頻率可以討論的除了質詢論述效率以外，還與情感投射有關，是拉近（或疏遠）心裡距離的常用手段，要如何判斷該詞當下的功用。


#倫理問題


無
