---
title: "LocationPart"
author: "Tim Lin"
date: "2017/12/25"
output: html_document
---

```{r read}
library(readr)
library(stringr)
userdata_all <- read.csv("~/Downloads/userdata_all.csv", header= F)
userdata_les <- read.csv("~/Downloads/userdata_lesbian.csv", header= F)

country_all<-userdata_all$V7
country_all<-str_replace_all(country_all, "_Occupation", "")
country_all<-str_replace_all(country_all, "_Profile", "")
country_all<-str_replace_all(country_all, "_Interests", "")
country_all<-str_replace_all(country_all, "_Turn", "")
country_all<-str_replace_all(country_all, "_Favorite", "")
country_all<-str_replace_all(country_all, "_Company", "")
country_all<-str_replace_all(country_all, "_School", "")
country_all<-str_replace_all(country_all, "_and", "")
country_all<-str_replace_all(country_all, "_", " ")

country_all<-str_replace_all(country_all, "United Kingdom", "UK")
country_all<-str_replace_all(country_all, "United States", "USA")
country_all<-str_replace_all(country_all, "usa", "USA")
country_all<-str_replace_all(country_all, "United Arab", "United Arab Emirates")
country_all<-str_replace_all(country_all, "nl", "Netherlands")
country_all<-str_replace_all(country_all, "Korea", "South Korea")
country_all<-str_replace_all(country_all, "Hong Kong", "China")

country_all_freq<-table(country_all)
country_all_freq<-as.data.frame(country_freq)
```

```{r cars}
library(ggplot2)
library(dplyr)


WorldData <- map_data('world')
WorldData %>% filter(region != "Antarctica") -> WorldData
WorldData <- fortify(WorldData)

df <- data.frame(region=country_all_freq$country_all, 
                 value=country_all_freq$Freq, 
                 stringsAsFactors=FALSE)


p <- ggplot()
p <- p + geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)
p <- p + geom_map(data=df, map=WorldData,
                  aes(fill=value, map_id=region),
                  colour="#7f7f7f", size=0.5)
p <- p + coord_map("rectangular", lat0=0, xlim=c(-180,180), ylim=c(-60, 90))
p <- p + scale_fill_continuous(low="thistle2", high="darkred", 
                               guide="colorbar")
p <- p + scale_y_continuous(breaks=c())
p <- p + scale_x_continuous(breaks=c())
p <- p + labs(fill="legend", title="Title", x="", y="")
p <- p + theme_bw()
p <- p + theme(panel.border = element_blank())
p 
```

```{r read}

country_les<-userdata_les$V7
country_les<-str_replace_all(country_les, "_Occupation", "")
country_les<-str_replace_all(country_les, "_Profile", "")
country_les<-str_replace_all(country_les, "_Interests", "")
country_les<-str_replace_all(country_les, "_Turn", "")
country_les<-str_replace_all(country_les, "_Favorite", "")
country_les<-str_replace_all(country_les, "_Company", "")
country_les<-str_replace_all(country_les, "_School", "")
country_les<-str_replace_all(country_les, "_and", "")
country_les<-str_replace_all(country_les, "_", " ")

country_les<-str_replace_all(country_les, "United Kingdom", "UK")
country_les<-str_replace_all(country_les, "United States", "USA")
country_les<-str_replace_all(country_les, "usa", "USA")
country_les<-str_replace_all(country_les, "United Arab", "United Arab Emirates")
country_les<-str_replace_all(country_les, "nl", "Netherlands")
country_les<-str_replace_all(country_les, "Korea", "South Korea")
country_les<-str_replace_all(country_les, "Hong Kong", "China")

country_les_freq<-table(country_les)
country_les_freq<-as.data.frame(country_les_freq)
```

```{r cars}

WorldData <- map_data('world')
WorldData %>% filter(region != "Antarctica") -> WorldData
WorldData <- fortify(WorldData)

df <- data.frame(region=country_les_freq$country_les, 
                 value=country_les_freq$Freq, 
                 stringsAsFactors=FALSE)


p <- ggplot()
p <- p + geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)
p <- p + geom_map(data=df, map=WorldData,
                  aes(fill=value, map_id=region),
                  colour="#7f7f7f", size=0.5)
p <- p + coord_map("rectangular", lat0=0, xlim=c(-180,180), ylim=c(-60, 90))
p <- p + scale_fill_continuous(low="thistle2", high="darkred", 
                               guide="colorbar")
p <- p + scale_y_continuous(breaks=c())
p <- p + scale_x_continuous(breaks=c())
p <- p + labs(fill="legend", title="Title", x="", y="")
p <- p + theme_bw()
p <- p + theme(panel.border = element_blank())
p 
```
